# Importing Modules/Packages
How to use stuff other people have written so that you don't have to reinvent the wheel.

## Modules

- Any python script that ends in .py can be a module
- People have written helper modules for most common tasks in python
- You hoose which modules to load so python starts up quickly

## Packages
- Collection of scripts that do common things
- NumPy: lots of scripts to help with calculating things in python

### PyPi: Python Package Index
- The place where you can find all these nifty modules
- https://pypi.python.org/pypi
- Wheels- pre-built distribution format that provides faster installation than installing a package from source

### Popular Packages
- NumPy
- SciPy
- Pandas
- Requests
- BeautifulSoup
- IPython
- NLTK
- Virtualenv

https://pythontips.com/2013/07/30/20-python-libraries-you-cant-live-without/

## Installing Modules

### Pip
Python's installer. Comes bundled with python 3>. 

### Setuptools
- Collection of enhancements to the Python distutils
- Allow you to more easily build and distribute Python packages
- Good for dealing with packages that have many dependencies

### Source
If no wheel is found on PyPi, you can try installing from source code
- Usually found on github, bitbucket, etc. 
- Google "package name source"
- Download the source file
- Use pip to install it

### Package Managers 
#### Mac: Homebrew
- Allows you to install things just like with pip
- brew install package
- http://brew.sh/
#### Linux: apt get
- apt get package
#### Windows: Download and install
- Download and install just like usual

## The Import Statement
Now that we've installed a package, how do we use it? 

In [10]:
# import all modules, submodules, and functions
import numpy
numpy.array([1,2,3])

array([1, 2, 3])

In [11]:
# alias it for lazy typing
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [12]:
# import all functions from numpy
from numpy import * 

# this loads everything into your local namespace and is not recommended

In [13]:
# preferred method, import only needed functions
from numpy import array as na, vectorize as nv

In [16]:
na([1,2,3])

array([1, 2, 3])

### Getting Help 

In [17]:
dir(numpy)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_globals',
 '_import_tools',
 '_mat',
 'abs',
 'absolute',
 'a

In [19]:
help(numpy.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).